# Unity catalog location
catalog: "hanna_moazam"
schema: "dspy"

# Chat/embedding models
chat_model_name: "system.ai.llama_v3_2_3b_instruct"
chat_endpoint_name: "meta-llama-3-2-3b-instruct-hanna"

embedding_model_name: "system.ai.gte_large_en_v1_5"
embedding_endpoint_name: "gte_large_en_v1_5_hanna"

# Vector search
vector_search_endpoint: "one-env-shared-endpoint-5"
vector_search_index: "dspy_cookbook_index"

# The name of your agent
agent_name: "dspy_cookbook_agent"

# Access token
secret_scope_name : "luis_moros_secrets"
secret_key: "general_tasks_pat"

